In [3]:
import os

print(os.path.exists(r"G:\My Drive\datasets\train.json"))

True

In [4]:
import os

print(os.listdir(r"G:\My Drive"))

['Classroom', 'Audio overviews', 'Colab Notebooks', 'datasets', 'ML_Projects', 'College_Dump', 'misc', 'desktop.ini']

In [5]:
import pandas as pd

In [6]:
df = pd.read_json(r"G:\My Drive\datasets\train.json")

In [7]:
df

          id      cuisine                                        ingredients
0      10259        greek  [romaine lettuce, black olives, grape tomatoes...
1      25693  southern_us  [plain flour, ground pepper, salt, tomatoes, g...
2      20130     filipino  [eggs, pepper, salt, mayonaise, cooking oil, g...
3      22213       indian                [water, vegetable oil, wheat, salt]
4      13162       indian  [black pepper, shallots, cornflour, cayenne pe...
...      ...          ...                                                ...
39769  29109        irish  [light brown sugar, granulated sugar, butter, ...
39770  11462      italian  [KRAFT Zesty Italian Dressing, purple onion, b...
39771   2238        irish  [eggs, citrus fruit, raisins, sourdough starte...
39772  41882      chinese  [boneless chicken skinless thigh, minced garli...
39773   2362      mexican  [green chile, jalapeno chilies, onions, ground...

[39774 rows x 3 columns]

In [8]:
pd.read_json('https://api.exchangerate-api.com/v4/latest/INR')

,provider,WARNING_UPGRADE_TO_V6,terms,base,date,time_last_updated,rates
INR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-13,1783900801,1.0000
AED,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-13,1783900801,0.0385
AFN,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-13,1783900801,0.6800
ALL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-13,1783900801,0.8610
AMD,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-13,1783900801,3.8500
...,...,...,...,...,...,...,...
YER,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-13,1783900801,2.4900
ZAR,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-13,1783900801,0.1710
ZMW,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-13,1783900801,0.1890
ZWG,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-13,1783900801,0.2800
ZWL,https://www.exchangerate-api.com,https://www.exchangerate-api.com/docs/free,https://www.exchangerate-api.com/terms,INR,2026-07-13,1783900801,0.2800

In [9]:
!pip install mysql.connector

Requirement already satisfied: mysql.connector in .\anaconda3\envs\machine_learning\Lib\site-packages (2.2.9)

In [1]:
import sys
print(sys.executable)

import mysql.connector
print(mysql.connector.__version__)

C:\Users\Anjli Kumari\python.exe
9.7.0

In [10]:
import mysql.connector

In [6]:
import sys
print(sys.executable)

C:\Users\Anjli Kumari\python.exe

In [12]:
pip show mysql-connector

Name: mysql-connector
Version: 2.2.9
Summary: MySQL driver written in Python
Home-page: http://dev.mysql.com/doc/connector-python/en/index.html
Author: Oracle and/or its affiliates
Author-email:
License: GNU GPLv2 (with FOSS License Exception)
Location: C:\Users\Anjli Kumari\Lib\site-packages
Requires:
Required-by:
Note: you may need to restart the kernel to use updated packages.

In [15]:
conn = mysql.connector.connect(host='localhost',port=3307,user='root',password='',database='world')

In [26]:
import pandas as pd
pd.read_sql_query("SELECT * FROM city where CountryCode LIKE 'USA'",conn)

C:\Users\Anjli Kumari\AppData\Local\Temp\ipykernel_20736\2180636485.py:2: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  pd.read_sql_query("SELECT * FROM city where CountryCode LIKE 'USA'",conn)

       ID          Name CountryCode        District  Population
0    3793      New York         USA        New York     8008278
1    3794   Los Angeles         USA      California     3694820
2    3795       Chicago         USA        Illinois     2896016
3    3796       Houston         USA           Texas     1953631
4    3797  Philadelphia         USA    Pennsylvania     1517550
..    ...           ...         ...             ...         ...
269  4062       Kenosha         USA       Wisconsin       89447
270  4063         Elgin         USA        Illinois       89408
271  4064        Odessa         USA           Texas       89293
272  4065        Carson         USA      California       89089
273  4066    Charleston         USA  South Carolina       89063

[274 rows x 5 columns]