In [2]:
df = pd.read_csv(r"\Users\Anjli Kumari\datasets\rsna_train.csv")
df

,StudyInstanceUID,Report,ACL,MCL,Medial Meniscus,Lateral Meniscus,Medial OA,Lateral OA,PF OA,Effusion,Synovitis,Baker's,Contusion,Fracture
0,1.2.826.0.1.3680043.8.498.10004873229099053869...,Técnica: RMN de la rodilla. Resultados: Rotura...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1.2.826.0.1.3680043.8.498.10004945927472656027...,[DATE]: * MR Knie Rechts 15ch AA Klinische Inl...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,1.2.826.0.1.3680043.8.498.10009278692606631573...,Hallazgos:\nNo hay alteraciones en significati...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,1.2.826.0.1.3680043.8.498.10009639203170750274...,"In the medial compartment, the meniscus is no...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,1.2.826.0.1.3680043.8.498.10013663742400736029...,CONSTATATIONS :\n\nFractures :\nAucune.\n\nAli...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4402,1.2.826.0.1.3680043.8.498.99880021280666757817...,Exam Type: MRI KNEE RIGHT WO CONTRAST\nExam Da...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4403,1.2.826.0.1.3680043.8.498.99881620336512626242...,[DATE]: *MR Knie Rechts 15ch AA Klinische Inli...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4404,1.2.826.0.1.3680043.8.498.99926624968240681772...,"SAĞ DİZ MRG. Tetkik protokolü: Çok düzlemli, ç...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4405,1.2.826.0.1.3680043.8.498.99939100657291954890...,"MRI of Knee with \n-Locator, SG PD FatSat, SG ...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4406,1.2.826.0.1.3680043.8.498.99957611207313098696...,Técnica: RMN de la rodilla. Resultados: Rotura...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
df.shape

(4407, 14)

In [6]:
df.isnull().mean()*100

StudyInstanceUID     0.000000
Report               0.000000
ACL                 98.683912
MCL                 98.683912
Medial Meniscus     98.683912
Lateral Meniscus    98.683912
Medial OA           98.683912
Lateral OA          98.683912
PF OA               98.683912
Effusion            98.683912
Synovitis           98.683912
Baker's             98.683912
Contusion           98.683912
Fracture            98.683912
dtype: float64

In [7]:
df.describe()

,ACL,MCL,Medial Meniscus,Lateral Meniscus,Medial OA,Lateral OA,PF OA,Effusion,Synovitis,Baker's,Contusion,Fracture
count,58.000000,58.000000,58.000000,58.000000,58.000000,58.000000,58.000000,58.000000,58.000000,58.000000,58.000000,58.000000
mean,0.413793,0.155172,0.448276,0.396552,0.258621,0.189655,0.362069,0.603448,0.465517,0.206897,0.327586,0.310345
std,0.496814,0.365231,0.501661,0.493454,0.441701,0.395452,0.484796,0.493454,0.503166,0.408619,0.473432,0.466675
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
75%,1.000000,0.000000,1.000000,1.000000,0.750000,0.000000,1.000000,1.000000,1.000000,0.000000,1.000000,1.000000
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [8]:
df_copy = df.copy()

In [11]:
missing_values = df_copy['ACL'].isnull()
df_copy.loc[missing_values, 'ACL'] = df_copy['ACL'].dropna().sample(df_copy['ACL'].isnull().sum()).values

ValueError: Cannot take a larger sample than population when 'replace=False'

In [26]:
for col in df_copy.drop(columns=['StudyInstanceUID', 'Report']).columns:
    print(f"{col} Analytics")
    print("Missing:", df_copy[col].isnull().sum())
    print("Available:", df_copy[col].notnull().sum())
print(df_copy.drop(columns=['StudyInstanceUID', 'Report']).shape[1])

ACL Analytics
Missing: 4349
Available: 58
MCL Analytics
Missing: 4349
Available: 58
Medial Meniscus Analytics
Missing: 4349
Available: 58
Lateral Meniscus Analytics
Missing: 4349
Available: 58
Medial OA Analytics
Missing: 4349
Available: 58
Lateral OA Analytics
Missing: 4349
Available: 58
PF OA Analytics
Missing: 4349
Available: 58
Effusion Analytics
Missing: 4349
Available: 58
Synovitis Analytics
Missing: 4349
Available: 58
Baker's Analytics
Missing: 4349
Available: 58
Contusion Analytics
Missing: 4349
Available: 58
Fracture Analytics
Missing: 4349
Available: 58
12

In [38]:
df.info(show_counts=np.nan)

<class 'pandas.DataFrame'>
RangeIndex: 4407 entries, 0 to 4406
Data columns (total 14 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   StudyInstanceUID  4407 non-null   str
 1   Report            4407 non-null   str
 2   ACL               58 non-null     float64
 3   MCL               58 non-null     float64
 4   Medial Meniscus   58 non-null     float64
 5   Lateral Meniscus  58 non-null     float64
 6   Medial OA         58 non-null     float64
 7   Lateral OA        58 non-null     float64
 8   PF OA             58 non-null     float64
 9   Effusion          58 non-null     float64
 10  Synovitis         58 non-null     float64
 11  Baker's           58 non-null     float64
 12  Contusion         58 non-null     float64
 13  Fracture          58 non-null     float64
dtypes: float64(12), str(2)
memory usage: 482.1 KB

In [52]:
df1 = pd.DataFrame([x.strip() for x in df['Report'][0].split('.') if x.strip()])
df1

                                                   0
0                         Técnica: RMN de la rodilla
1              Resultados: Rotura de menisco interno
2  Signo de necrosis avascular subcondral en el c...
3                       Artrosis femorotibial medial
4                                            Derrame
5               Impresión: Rotura de menisco interno
6  Signo de necrosis avascular subcondral en el c...
7                       Artrosis femorotibial medial
8                                            Derrame

In [56]:
df2 = pd.DataFrame(df['Report'].apply(lambda x: [s.strip() for s in str(x).split('.') if s.strip()]).tolist())
df2 = df2.iloc[0:,0:10]
df2

,0,1,2,3,4,5,6,7,8,9
0,Técnica: RMN de la rodilla,Resultados: Rotura de menisco interno,Signo de necrosis avascular subcondral en el c...,Artrosis femorotibial medial,Derrame,Impresión: Rotura de menisco interno,Signo de necrosis avascular subcondral en el c...,Artrosis femorotibial medial,Derrame,NaN
1,[DATE]: * MR Knie Rechts 15ch AA Klinische Inl...,Diagnostische vraagstellling: Meniscusscheur/m...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,Hallazgos:\nNo hay alteraciones en significati...,Ligamentos cruzados y colaterales dentro de lí...,Aumento de señal del cuerno posterior del meni...,Menisco lateral de morfología y señal conserva...,Úlceras condrales de espesor parcial con fenóm...,El resto de los cartílagos femorotibiales y de...,Úlceras condrales espesor parcial de la rótula...,No hay evidente derrame articular ni quistes p...,Engrosamiento y aumento de señal del tercio pr...,"Tendones de la pata de ganso, bíceps femoral y..."
3,"In the medial compartment, the meniscus is not...","The lateral compartment, there is suspicious i...",There is no focal chondrosis or chondral injury,"The patellofemoral joint, the patellar and tro...",The medial patellofemoral ligament is intact,"In the intercondylar notch, the anterior and p...",There is no tibial translation,The medial collateral ligament complexes are i...,The posteromedial oblique ligament is intact,The lateral collateral ligament complexes are ...
4,CONSTATATIONS :\n\nFractures :\nAucune,Alignement articulaire :\nNormal,Changements dégénératifs :\nChondropatie rétro...,Chondropatie légère des surfaces portantes des...,Signal de la moelle osseuse :\nPar ailleurs no...,Ligament croisé antérieur : Normal,Ligament croisé postérieur : Normal,Ligament collatéral médial : Léger épaississem...,Complexe du ligament collatéral latéral : normal,Ménisque médial : Légers changements dégénérat...
...,...,...,...,...,...,...,...,...,...,...
4402,Exam Type: MRI KNEE RIGHT WO CONTRAST\nExam Da...,Comparison: No relevant prior studies availabl...,TECHNIQUE:\nMRI of the right knee was performe...,5 Tesla system with a dedicated knee coil in t...,FINDINGS:\nOSSEOUS STRUCTURES:\nMild bone marr...,No acute fracture or bone bruise,Background marrow signal is normal without inf...,No aggressive osseous lesions,JOINT SPACE:\nSmall joint effusion,"Mild, diffuse synovial proliferation"
4403,[DATE]: *MR Knie Rechts 15ch AA Klinische Inli...,Diagnostische vraagstellling: Meniscusletsel ?...,"(T2-hyperintense) ""bone-bruise"" laesies latera...",laaggradige sprain proximale insertie lateraal...,Verder: Normale configuratie signaalalteraties...,NaN,NaN,NaN,NaN,NaN
4404,SAĞ DİZ MRG,"Tetkik protokolü: Çok düzlemli, çok sekanslı",Bulgular: Medial menisküste grade II dejeneras...,Medial menisküs posterior komşuluğunda yaklaşı...,Lateral menisküste grade III dejenerasyon ve h...,"Ön çapraz bağ ve arka çapraz bağ, lateral ve m...",Distal kuadriseps ve patellar tendonlar normaldir,Patella normal yerleşimlidir,Retinaküler devamsızlık yoktur,Patellar kıkırdakta yer yer hipointens değişik...
4405,"MRI of Knee with \n-Locator, SG PD FatSat, SG ...",> Mild fat stranding over infrapatellar fat pad,> The contour of ACL & PCL appear to be within...,> No strong MR evidence of tear is noted in e...,> Both medial & lateral collateral ligaments a...,> No evidence of bone contusion is noted,> Some joint effusion\nImpression: \n1,R/O grade 2 patellar chondromalacia,2,"Mild fat stranding over infrapatellar fat pad,..."
4406,Técnica: RMN de la rodilla,Resultados: Rotura de fibras del tendón rotuliano,Impresión: Rotura de fibras del tendón rotuliano,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [ ]:
X_train,X_test,Y_train,Y_test = train(X,Y,0.2,42)